//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libray
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Libray_bookEntities : DbContext
    {
        private static Libray_bookEntities _context;

        public Libray_bookEntities()
            : base("name=Libray_bookEntities")
        {
        }

        public static Libray_bookEntities GetContext()
        {
            if ( _context == null )
                _context = new Libray_bookEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Reader> Readers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Librarian> Librarians { get; set; }
        public virtual DbSet<Recording> Recordings { get; set; }
    }
}
